"""Evolving AI package - new core architecture."""

from .core import (
    Genome,
    DenseGenome,
    Task,
    XorTask,
    SequencePredictionTask,
    create_task,
    ArchiveEntry,
    NoveltyArchive,
    MapElitesArchive,
    EvolutionEngine,
    EvolutionConfig,
    EvaluatedCandidate,
    GenerationSummary,
    EvolutionRuntime,
    # CEP-1 Constitutional Evolution Protocol
    CEPEvolutionEngine,
    IntentPattern,
    ConstitutionalGenome,
    EvidenceRecord,
    LineageRecord,
    ConstitutionalCandidate,
    CEPGenerationSummary,
    PromotionTier,
    MutationOperatorType,
    RMLCMetaLearner,
    CEPForgeEvaluator,
    ConstitutionalSelection,
)
from .core.config import (
    ConfigBase,
    EvolutionConfig as CoreEvolutionConfig,
    TaskConfig,
    ArchiveConfig,
    ExperimentConfig,
)
from .core.plugins import (
    PluginRegistry,
    task_registry,
    archive_registry,
    engine_registry,
    genome_registry,
    register_task,
    register_archive,
    register_engine,
    register_genome,
)
from .aris.runtime import ArisRuntime
from .engines import (
    CEPOrchestrationService,
    CEPOrchestrationConfig,
    CEPArisIntegration,
    CEPArisIntegrationConfig,
)
from .engines.advanced import (
    SpeciationEngine,
    MapElitesEngine,
    NSGA2Engine,
    CMAESEngine,
)
from .genomes.cppn import (
    CPPNNode,
    CPPNGenome,
    CPPNSubstrate,
    create_hyperneat_substrate,
)
from .genomes.graph import (
    GraphNode,
    GraphConnection,
    GraphGenome,
    ModuleGenome,
)
from .tasks.rl import (
    RLTask,
    GymTask,
    ProcgenTask,
    PyBulletTask,
    IsaacGymTask,
    MultiAgentTask,
    CoevolutionTask,
    create_rl_task,
)
from .meta.meta_learning import (
    MetaGenome,
    MetaTask,
    OptimizerMetaGenome,
    LossFunctionGenome,
    ActivationGenome,
    ArchitectureGenome,
    MetaEvolutionEngine,
    ContinualEvolutionEngine,
    EvolutionaryDistillationEngine,
)
from .runtime.distributed import (
    DistributedBackend,
    ThreadPoolBackend,
    ProcessPoolBackend,
    RayBackend,
    DaskBackend,
    DaskOnRayBackend,
    DistributedEvolutionConfig,
    DistributedEvolutionEngine,
    IslandModelEngine,
    create_distributed_engine,
    create_island_engine,
)
from .open_ended.open_ended import (
    OpenEndedTask,
    LLMMutationEngine,
    EvolutionaryPromptingEngine,
    EmergentCommunicationTask,
    QuantumInspiredGenome,
    OpenEndedEvolutionEngine,
    create_llm_engine,
    create_prompt_engine,
    create_open_ended_engine,
)

__all__ = [
    # Core
    "Genome",
    "DenseGenome",
    "Task",
    "XorTask",
    "SequencePredictionTask",
    "create_task",
    "ArchiveEntry",
    "NoveltyArchive",
    "MapElitesArchive",
    "EvolutionEngine",
    "EvolutionConfig",
    "EvaluatedCandidate",
    "GenerationSummary",
    "EvolutionRuntime",
    "ConfigBase",
    "CoreEvolutionConfig",
    "TaskConfig",
    "ArchiveConfig",
    "ExperimentConfig",
    "PluginRegistry",
    "task_registry",
    "archive_registry",
    "engine_registry",
    "genome_registry",
    "register_task",
    "register_archive",
    "register_engine",
    "register_genome",
    "ArisRuntime",
    # CEP-1 Constitutional Evolution Protocol
    "CEPEvolutionEngine",
    "IntentPattern",
    "ConstitutionalGenome",
    "EvidenceRecord",
    "LineageRecord",
    "ConstitutionalCandidate",
    "CEPGenerationSummary",
    "PromotionTier",
    "MutationOperatorType",
    "RMLCMetaLearner",
    "CEPForgeEvaluator",
    "ConstitutionalSelection",
    # Advanced engines
    "SpeciationEngine",
    "MapElitesEngine",
    "NSGA2Engine",
    "CMAESEngine",
    # Advanced genomes
    "CPPNNode",
    "CPPNGenome",
    "CPPNSubstrate",
    "create_hyperneat_substrate",
    "GraphNode",
    "GraphConnection",
    "GraphGenome",
    "ModuleGenome",
    # RL tasks
    "RLTask",
    "GymTask",
    "ProcgenTask",
    "PyBulletTask",
    "IsaacGymTask",
    "MultiAgentTask",
    "CoevolutionTask",
    "create_rl_task",
    # Meta-learning
    "MetaGenome",
    "MetaTask",
    "OptimizerMetaGenome",
    "LossFunctionGenome",
    "ActivationGenome",
    "ArchitectureGenome",
    "MetaEvolutionEngine",
    "ContinualEvolutionEngine",
    "EvolutionaryDistillationEngine",
    # Distributed runtime
    "DistributedBackend",
    "ThreadPoolBackend",
    "ProcessPoolBackend",
    "RayBackend",
    "DaskBackend",
    "DaskOnRayBackend",
    "DistributedEvolutionConfig",
    "DistributedEvolutionEngine",
    "IslandModelEngine",
    "create_distributed_engine",
    "create_island_engine",
    # Open-ended
    "OpenEndedTask",
    "LLMMutationEngine",
    "EvolutionaryPromptingEngine",
    "EmergentCommunicationTask",
    "QuantumInspiredGenome",
    "OpenEndedEvolutionEngine",
    "create_llm_engine",
    "create_prompt_engine",
    "create_open_ended_engine",
]